### ISSUE TITLE
Error for GPU version

### ISSUE THREAD

**Issue by Jevin754** [zh217/torch-asg#2]
Hi, the CPU implementation is installed successfully with gcc 6+. However, an error "nvcc fatal: Unsupported gpu architecture 'compute_75'" appeared while installing the latest GPU implementation. The working enrionment is as follows:
GPU-GTX1080Ti, CUDA-9.0, cuDNN-7.0, gcc 6+.
Could you please tell me the CUDA and cuDNN version on your machine while you are testing the GPU implementation? Thank you so much~

**Comment by zh217** [comment]
Hi, you will need CUDA 10 for compute_75. But since your card does not support compute_75 anyway, you can actually just comment out the relevant lines in setup.py and it should install successfully with CUDA 9.
